import { ONE_PROBE_90PC, ONE_PROBE_90PC_4CONFIGS, ONE_PROBE_90PC_RANDOM, TWENTY_PROBE_50PC_RANDOM, TWENTY_PROBE_50PC_SHARED_RANDOM, TWO_PROBE_90PC_4CONFIGS, TWO_PROBE_90PC_NO_OVERLAP, TWO_PROBE_90PC_OVERLAP, TWO_PROBE_90PC_RANDOM, TWO_PROBE_90PC_SHARED_RANDOM } from './scenarios/probe_success.ts'
import { TIME_RANGES } from './timeRanges.ts'
import { writeScenarios } from './writeScenarios.ts'

const labels = {
  job: "test_job",
  instance: "https://testinstance.com",
}

writeScenarios([
  ONE_PROBE_90PC,
  ONE_PROBE_90PC_RANDOM,
  TWO_PROBE_90PC_OVERLAP,
  TWO_PROBE_90PC_NO_OVERLAP,
  TWO_PROBE_90PC_RANDOM,
  TWO_PROBE_90PC_SHARED_RANDOM,
  ONE_PROBE_90PC_4CONFIGS,
  TWO_PROBE_90PC_4CONFIGS,

  TWENTY_PROBE_50PC_RANDOM,
  TWENTY_PROBE_50PC_SHARED_RANDOM,
], TIME_RANGES, labels)
